[build]
PHP_VERSION = 7.2

command = "source /opt/buildhome/.phpbrew/bashrc && phpbrew install 7.2.2 +default && phpbrew switch 7.2.2 && phpbrew app get composer && composer require tightenco/jigsaw && ./vendor/bin/jigsaw build"
publish = "/build_local"
